apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app_name}}
spec:
  selector:
    app: {{.Values.app_name}}
  type: NodePort
  ports:
    -  port: {{.Values.service_port}}
       targetPort: {{.Values.image.port}}
